name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      planet:
        description: 'Default planet to display'
        required: true
        default: 'moon'
        type: choice
        options:
          - moon
          - mars
          - mercury
          - venus
          - iss
          - jupiter
          - saturn

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set default planet
        run: |
          PLANET="${{ github.event.inputs.planet || 'moon' }}"
          echo "Setting default planet to: $PLANET"
          
          # Update the default planet in the JavaScript
          sed -i "s/const defaultPlanet = '[^']*'/const defaultPlanet = '$PLANET'/" index.html
          
          # Also update the selector to show the correct default
          sed -i "s/<option value=\"$PLANET\"/<option value=\"$PLANET\" selected/" index.html
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Create deployment info
        run: |
          echo "Deployed with featured planet: ${{ github.event.inputs.planet || 'moon' }}" > deployment-info.txt
          echo "Deployment date: $(date)" >> deployment-info.txt
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
